spring:
  application:
    name: times
  datasource:
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8787
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
project:
  winpath: F:\common\upload\
  otherospath: /Users/sdl/upload/
  profile: /profile/**
